ask/ask/urls.py
from django.conf.urls import patterns, url

from django.contrib import admin
from django.contrib.auth.views import login
admin.autodiscover()
from qa.views import (
    test, new_questions, popular_questions, question_detail, ask, answer,
    signup)


urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', test, name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
    url(r'^new/$', test, name='new'),
    url(r'^popular/$', popular_questions, name='popular'),
    url(r'^ask/', ask, name='ask'),
    url(r'^answer/', answer, name='answer'),
    url(r'^question/(?P<question_id>[0-9]+)/$', question_detail,
        name='question_detail'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^login/$', login, {'template_name': 'qa/login.html'}, name='login'),
    url(r'^$', new_questions, name='index'),
)

ask/qa/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    title = models.CharField(max_length=55)
    text = models.TextField()
    added_at = models.DateField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    author = models.ForeignKey(User, null=True, blank=True,
                               related_name='author_set')
    likes = models.ManyToManyField(User, null=True, blank=True,
                                   related_name='likes_set')


class Answer(models.Model):
    text = models.TextField()
    added_at = models.DateField(auto_now_add=True)
    question = models.ForeignKey(Question)
    author = models.ForeignKey(User, null=True, blank=True)

ask/qa/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from qa.models import Question, Answer


class AskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(AskForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(AskForm, self).save(commit=False)
        if not self.user.is_anonymous():
            instance.author = self.user
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Question
        fields = ('title', 'text')


class AnswerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(AnswerForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(AnswerForm, self).save(commit=False)
        if not self.user.is_anonymous():
            instance.author = self.user
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Answer
        fields = ('text', 'question')
        widgets = {'question': forms.HiddenInput()}


#class MyUserCreationForm(UserCreationForm):
#    class Meta:
#        model = User
#        fields = ('username', 'email')


class MyUserCreationForm(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def save(self, commit=True):
        user = super(MyUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ('username', 'email')

ask/qa/views.py
from django.shortcuts import render, render_to_response, get_object_or_404, redirect
from django.http import HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import authenticate, login
#from django.contrib.auth.forms import UserCreationForm
from qa.models import Question
from qa.forms import AskForm, AnswerForm, MyUserCreationForm


def test(request, *args, **kwargs):
    return HttpResponse('OK')


def new_questions(request):
    limit = 10
    page = request.GET.get('page')
    paginator = Paginator(Question.objects.all().order_by('-pk'), limit)
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)
    return render_to_response(
        'qa/questions_list.html', {'questions': questions})


def popular_questions(request):
    limit = 10
    page = request.GET.get('page')
    paginator = Paginator(Question.objects.all().order_by('-rating'), limit)
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)
    return render_to_response(
        'qa/questions_list.html', {'questions': questions})


def question_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    form = AnswerForm(initial={'question': question_id})
    return render(request, 'qa/question_detail.html',
                  {'question': question, 'form': form})


def ask(request):
    if request.method == 'POST':
        form = AskForm(request.POST, user=request.user)
        if form.is_valid():
            question = form.save()
            return redirect('question_detail', question_id=question.id)
    else:
        form = AskForm(user=request.user)
    return render(request, 'qa/ask.html', {'form': form})


def answer(request):
    if request.method == 'POST':
        form = AnswerForm(request.POST, user=request.user)
        if form.is_valid():
            answer = form.save()
            return redirect('question_detail', question_id=answer.question_id)
    #else:
    #    form = AskForm(user=request.user)
    #return render(request, 'qa/ask.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'])
            login(request, user)
            return redirect('index')
    else:
        form = MyUserCreationForm()
    return render(request, 'qa/signup.html', {'form': form})

ask/qa/templates/qa/ask.html
{% extends 'base.html' %}

{% block content %}

    <form action="{% url 'ask' %}" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>

{% endblock content%}

ask/qa/templates/qa/login.html
{% extends 'base.html' %}

{% block content %}

    <form action="{% url 'login' %}" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>

{% endblock content%}

ask/qa/templates/qa/question_detail.html
{% extends 'base.html' %}

{% block content %}

    {{ question.title }}<br>
    {{ question.text }}<br>
    Answers:<br>
    {% for answer in question.answer_set.all %}
        {{ answer.text }}<br>
    {% endfor %}

    Add answer:<br>
    <form action="{% url 'answer' %}" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>

{% endblock content%}

ask/qa/templates/qa/questions_list.html
{% extends 'base.html' %}

{% block content %}

    {% for question in questions %}
        {{ question.title }} - <a href="{% url 'question_detail' question.pk %}">Перейти к вопросу {{ question.pk }}</a><br />
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if questions.has_previous %}
                <a href="?page={{ questions.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ questions.number }} of {{ questions.paginator.num_pages }}.
            </span>

            {% if questions.has_next %}
                <a href="?page={{ questions.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>

{% endblock content%}

ask/qa/templates/qa/signup.html
{% extends 'base.html' %}

{% block content %}

    <form action="{% url 'signup' %}" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>

{% endblock content%}

templates/base.html
<!DOCTYPE html>
<html>
    <body>
        {% block content %}{% endblock content %}
    </body>
</html>